### ISSUE TITLE
Error retrieving Apex docs

### ISSUE THREAD

**Issue by nchursin** [Oblongmana/sublime-salesforce-reference#33]
Got an error when tried to some docs for Apex:
```
Traceback (most recent call last):
  File "/Users/nchursin/Library/Application Support/Sublime Text 3/Packages/Salesforce Reference/salesforce_reference/retrieve.py", line 86, in run
    for toc_entry in getAllTocLeafParents(next(reference_toc),None):
StopIteration
```
Just tried to execute `Salesforce Reference - Apex`.
Please fix it.
All other commands work fine.

P.S. Pretty helpful tool. Thanks for making it.

**Comment by ralphcallaway** [comment]
running into the same issue :-/, missing the apex docs a ton, i've gotten hooked on this awesome package

let me know if i can be of any assistance with debugging info ...

```
######### Sublime Salesforce Reference Error #########
Fatal error in Sublime Salesforce Reference while retrieving doc. Please report this on https://github.com/Oblongmana/sublime-salesforce-reference/issues. Error info follows:
Traceback (most recent call last):
  File "/Users/ralphcallaway/Library/Application Support/Sublime Text 3/Packages/Salesforce Reference/salesforce_reference/retrieve.py", line 86, in run
    for toc_entry in getAllTocLeafParents(next(reference_toc),None):
StopIteration
```

**Comment by Oblongmana** [comment]
Hey @ralphcallaway @nchursin - have just pushed out a new update fixing this (`2.1.1`). From memory, it generally takes up to hour before Package Control checks for updates. Feel free to reopen this if you have any issues with the fix!

**Comment by ralphcallaway** [comment]
@Oblongmana looking good, fyi, i'd gotten the package control message that it was upgraded, but it initially failed, after restarting it started working

thanks for helping, i really love this tool! it's made a big difference in my workflow
